# Generated by Django 2.2.5 on 2020-11-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201119_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_posted',
            new_name='published_comment',
        ),
    ]
